version: '3'
services:
  client:
    container_name: client-container
    image: jeanaush/img-a:18.19.1
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - yolo-network
    volumes:
      - client-volume:/app
    depends_on:
      - backend
  backend:
    container_name: backend-container
    image: jeanaush/img-b:18.19.1
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - yolo-network
    volumes:
      - backend-volume:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
  mongodb:
    container_name: yolo-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - yolo-network
    volumes:
      - mongodb-data:/data/db
volumes:
  backend-volume:
  client-volume:
  mongodb-data:

networks:
  yolo-network:
    driver: bridge
