---
- name: Pull frontend Docker image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Start frontend container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    restart_policy: always
    network_mode: "{{ docker_network_name }}"
    ports:
      - "{{ frontend_port }}:3000"
    env:
      NODE_ENV: "{{ node_env }}"
      REACT_APP_API_URL: "http://localhost:{{ backend_port }}/api"

- name: Wait for frontend to be ready
  uri:
    url: "http://localhost:{{ frontend_port }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1